// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYM5uM0k4-ohluuEwGK5djwWb-4PpB3ig',
    appId: '1:294218974682:web:52623982e3439ba61eece3',
    messagingSenderId: '294218974682',
    projectId: 'heartfelt-hands-cf536',
    authDomain: 'heartfelt-hands-cf536.firebaseapp.com',
    storageBucket: 'heartfelt-hands-cf536.appspot.com',
    measurementId: 'G-R048902VSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDKscrkT-s1RzW2GTS3Dgv_Mbrw3wJLQw',
    appId: '1:294218974682:android:261643297b8bd3751eece3',
    messagingSenderId: '294218974682',
    projectId: 'heartfelt-hands-cf536',
    storageBucket: 'heartfelt-hands-cf536.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB99JJYTE-i0lcN1sk3yP2TuMSNPp5LP8c',
    appId: '1:294218974682:ios:bf96934674a92f191eece3',
    messagingSenderId: '294218974682',
    projectId: 'heartfelt-hands-cf536',
    storageBucket: 'heartfelt-hands-cf536.appspot.com',
    iosBundleId: 'com.example.heartfeltHands',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB99JJYTE-i0lcN1sk3yP2TuMSNPp5LP8c',
    appId: '1:294218974682:ios:bf96934674a92f191eece3',
    messagingSenderId: '294218974682',
    projectId: 'heartfelt-hands-cf536',
    storageBucket: 'heartfelt-hands-cf536.appspot.com',
    iosBundleId: 'com.example.heartfeltHands',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYM5uM0k4-ohluuEwGK5djwWb-4PpB3ig',
    appId: '1:294218974682:web:73e6aa6cd22b2b931eece3',
    messagingSenderId: '294218974682',
    projectId: 'heartfelt-hands-cf536',
    authDomain: 'heartfelt-hands-cf536.firebaseapp.com',
    storageBucket: 'heartfelt-hands-cf536.appspot.com',
    measurementId: 'G-QJ57QPX1XN',
  );
}
