abstract class AppStrings {
  static const String appName = "HeartFelt Hands",
      skip = "تخطي",
      start = "ابدأ رحله الاحسان ",
      onBoardingTextOne =
          "فرص تبرع متنوعه \nتغطي معظم مجالات الخير وتصل الي\n من يستحقها من الفئات الأشد احتياجا",
      onBoardingTextTwo =
          "يصنع المتطوعون\n فرقا كل يوم\n تتيح المؤسسه الفرصه للمتطوعين للعمل في المجالات التي يعرفونها بشكل افضل",
      onBoardingTextThree =
          "متابعه الاحصائيات الخاصه عبر الاطلاع علي علي سجلات تبرعاتك من خلال حسابك الشخصي",
      donateNow = "تبرع الان",
      foodSurplus = "فائض طعامك ..  وجبة لغيرك ",
      donationChance = "فرص التبرع",
      more = "المزيد",
      providingMeals = "توفير وجبات الفطور للصائمين ",
      remaining = "المتبقي",
      amount = "10,000 ج.م",
      gratePhilanthropists = "كبار المحسنين",
      partners = "شركاء الإحسان ",
      ambassadors = "سفراء الإحسان ",
      settings = "الاعدادات",
      createAccount = "إنشاء حساب",
      fullName = "الاسم بالكامل*",
      email = "البريد الالكتروني*",
      password = "كلمة السر*",
      confirmPassword = "تأكيد كلمة السر*",
      phoneNumber = "رقم الجوال*",
      age = "العمر",
      gender = "الجنس",
      termsAndCondition = "اوافق على سياسة الخصوصية",
      statistics = "إحصائيات",
      yourDonations = "تبرعاتك :",
      numberOfDonation = "0",
      numberOfTimeDonation = "عدد مرات التبرع",
      totalAmounts = "إجمالي المبالغ",
      theAmount = "0 ج.م",
      totalNumberOfPoints = "إجمالي عدد النقاط",
      profilePersonly = "الملف الشخصي",
      donationRecord = "سجل التبرعات",
      paymentCards = "بطاقات الدفع",
      periodicDonation = "التبرع الدوري",
      logOut = "تسجيل الخروج",
      contribute = " ساهم في بناء جامع",
      doNotHaveAnyDonation = "ليس لديك تبرعات حالياً",
      addNewCard = "اضافة بطاقة جديدة",
      doNotHavePaymentCard = "ليس لديك بطاقات دفع مسجلة",
      periodicDonationService =
          "خدمة تتيح لك إمكانية خصم\n(استقطاع) مبلغ من بطاقتك البنكية\nللتبرع بشكل دوري، يصل إلى فرص \nالتبرع ذات الأولوية تلقائياً.",
      subTitleOne =
          "يسعى المشروع إلى بناء جامع متعدد المرافق والخدمات على طريق السريع؛ ليسهل على المسافرين أداء الصلاة في الأماكن المخصصة لها",
      donateYourMoney = "زكاة مالك",
      subTitleTwo =
          "عن طريق حاسبة الزكاة,لمعرفة مقدار الزكاة الواجبة ثم دفعها مباشرة.",
      charity = "صدقتك",
      subTitleThree =
          "صدقة جارية يدوم نفعها ويتضاعف أجرها, ساهم معنا في اوقاف مستدامة في مجالات البر المختلفة مثل :";
}
